services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - ./redis:/data
    networks:
      - backend

  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - backend

  celery:
    image: backend:latest
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs/
    command: ["uv", "run", "celery", "-A", "backend.src.tasks", "worker"]
    depends_on:
      - base
      - redis
    networks:
      - backend
    
  backend:
    image: backend:latest
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs/
    command: ["uv", "run", "main.py"]
    depends_on:
      - base
      - redis
      - database
      - celery
    networks:
      - backend

networks:
  backend: 
    driver: bridge